(in-package :lisprl)

(defparameter *screen-y* 0)
(defparameter *screen-x* 0)
(defparameter *player* nil)
(defparameter *objects* nil)
(defparameter *creature-list* nil)
(defparameter *running* t)
(defparameter *map-max-x* 80)
(defparameter *map-max-y* 25)
(defparameter *los-radius* 7)
(defparameter *message-box-y* 0)
(defparameter *message-box-x* (+ 2 *map-max-x*))
(defparameter *message-list* nil)
(defparameter *max-display-message* 5)
(defparameter *map* (make-array (list *map-max-x* *map-max-y*) :initial-element nil))
